vksearch/siteauth/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

import siteauth.views as siteauth

app_name = "siteauth"

urlpatterns = [
    path("signup/", siteauth.SiteUserCreateView.as_view(), name="signup"),
    path("settings/<int:pk>/", siteauth.SiteUserUpdateView.as_view(), name="settings"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

vksearch/vkgroup/urls.py
from django.urls import path

from .views import communities_view

app_name = "vkgroup"

urlpatterns = [
    path("", communities_view, name="search"),
]

vksearch/vksearch/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from vksearch.settings import DEBUG

from .view import index

urlpatterns = [
    path("", index, name="home"),
    path("vksearh/", include("vkgroup.urls", namespace="vkgroup")),
    path("siteauth/", include("siteauth.urls", namespace="siteauth")),
    path("admin/", admin.site.urls),
]

# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if DEBUG:
    urlpatterns += (path("__debug__/", include("debug_toolbar.urls")),)
if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vksearch/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.1/css/all.css"
          integrity="sha384-/frq1SRXYH/bSyou/HUp/hib7RVN1TawQYja658FEOodR/FQBKVqT9Ol+Oz3Olq5" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>
        {% block title %} {{ title }}
        {% endblock %}
    </title>

</head>

<body>
<nav class="navbar navbar-expand-lg navbar navbar-light"
     style="background-image: linear-gradient(-45deg, #7dc3f8,#4778fa)">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url "home" %}">Find your target audience!</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 top-menu">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "vkgroup:search" %}">Search</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">
                        <i class="far fa-user"></i></a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_anonymous %}
                        <li><a class="dropdown-item" href="{% url 'siteauth:login' %}">Login</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'siteauth:logout' %}">Logout</a></li>
                        <li><a class="dropdown-item" href="{% url 'siteauth:settings' user.pk %}">{{user.username}}</a></li>
                        {% endif %}
                        <li><a class="dropdown-item" href="{% url 'siteauth:signup' %}">Signup</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<!--<ul>-->
<!--    {% if messages %}-->
<!--    <ul class="messages">-->
<!--        {% for message in messages %}-->
<!--        {{ message }}-->
<!--        {% endfor %}-->
<!--    </ul>-->
<!--    {% endif %}-->
<!--</ul>-->

<!--<ul>-->
<!--    {% if user.is_anonymous %}-->
<!--    <li><a href="{% url "siteauth:login" %}">Login</a></li>-->
<!--    <li><a href="{% url "siteauth:signup" %}">Signup</a></li>-->
<!--    {% else %}-->
<!--    <li><a href="{% url "siteauth:logout" %}">Logout</a></li>-->
<!--    <li><a href="{% url "siteauth:settings" user.pk %}">{{user.username}}</a></li>-->
<!--    {% endif %}-->
<!--</ul>-->

{% block main_content %}


{% endblock %}

{% block menu %}

{% endblock %}


</body>
</html>

vksearch/templates/home.html
{% extends 'base.html' %}


{% block main_content %}
<h5>
    <br>
   The efficiency and success of advertising largely depend on target audience settings in VKontakte.
    <br>
    <br>
    Our site provides some options, using which you can select the necessary target audience among millions of users.
</h5>

{% endblock %}

vksearch/templates/paginator.html
<div >
    {% load url_replace %}

    {% if page_obj and page_obj.has_previous %}
      <a href="?{% url_replace page=page_obj.previous_page_number %}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </span>
    {% if page_obj and page_obj.has_next %}
      <a href="?{% url_replace page=page_obj.next_page_number %}">Next</a>
    {% endif %}
</div>